In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [2]:
if torch.cuda.is_available():
  print('GPU is Avalibalbe')
  print("GPU using : ",torch.cuda.get_device_name(0))
else:
  print('GPU is not available. Using CPU.')

GPU is Avalibalbe
GPU using :  Tesla T4


# ****Creating A Tensor****

In [3]:
# using empty

a = torch.empty(2,4)
a
# This Function is used to allocate memory. It creates space in memory.
# Shows Values already available in memory.

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
# Check type

type(a)

torch.Tensor

In [5]:
# Using Zeros

torch.zeros(2,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
# Using Ones

torch.ones(2, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [7]:
# Using rand

torch.rand(2, 5)

tensor([[0.7838, 0.3057, 0.9750, 0.2894, 0.3785],
        [0.9686, 0.6305, 0.6933, 0.5036, 0.4691]])

In [8]:
# Use of seed

torch.manual_seed(100)
torch.rand(2, 5)

# Here seed is used to generate same numbers.
# If we call rand it returns different values every time
# manual.seed is similar as random_state in sklearn

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180]])

In [9]:
# Using Tensor

torch.tensor([(1, 4, 5), (5, 3, 6)])

tensor([[1, 4, 5],
        [5, 3, 6]])

# ****Others Way****

In [10]:
# arange

print("By Using Arange -> ", torch.arange(1, 21, 2))

By Using Arange ->  tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])


In [11]:
# Using linspace

print('Using Linspace -> ', torch.linspace(1, 21, 5))

Using Linspace ->  tensor([ 1.,  6., 11., 16., 21.])


In [12]:
# using eye

print("Using eye -> \n",torch.eye(5))

# returns identity metrics

Using eye -> 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [13]:
# Using full
print('Using Full -> \n', torch.full((4, 4), 1))


# torch.ful((shape), return_item)

Using Full -> 
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


# ****Tensor Shape****

In [14]:
y = torch.tensor([[1, 5, 9, 7], [7, 1, 7, 5]])
y

tensor([[1, 5, 9, 7],
        [7, 1, 7, 5]])

In [15]:
y.shape

torch.Size([2, 4])

In [16]:
# Using Empty_like

torch.empty_like(y)

tensor([[135577754922384,       919465152,       919088160,       919396624],
        [              0,       919233088,       891033584, 135573171850848]])

In [17]:
# Using Zeros_like

torch.zeros_like(y)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [18]:
# Using Ones_like

torch.ones_like(y)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [19]:
# Using rand_like

torch.rand_like(y, dtype = torch.float64)

tensor([[0.9736, 0.6941, 0.3464, 0.9751],
        [0.7911, 0.4274, 0.4460, 0.5522]], dtype=torch.float64)

# ****Tensor Datatypes****

In [20]:
y.dtype

torch.int64

In [21]:
torch.tensor([1.312, 2.144, 7.452, 9.322, 4.234, 7.433, 6.754], dtype = torch.int64)

tensor([1, 2, 7, 9, 4, 7, 6])

In [22]:
# Using to
y.to(torch.float64)

tensor([[1., 5., 9., 7.],
        [7., 1., 7., 5.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# ****Mathematical Operations****

## ****1. Scalar Operations****

In [23]:
z = torch.rand(5, 5)
z

tensor([[0.7445, 0.4892, 0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235, 0.0169, 0.2209],
        [0.9535, 0.7064, 0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430, 0.3182, 0.5261],
        [0.0447, 0.5123, 0.9051, 0.5989, 0.4450]])

In [24]:
# ADDITION
print('Addition --> \n', z + 3)

# SUBSTRACTION
print('\nSubstraction --> \n', z - 1)

# MULTIPLICATION
print('\nMultiplication --> \n', z * 4)

# DIVISION
print('\nDivision -- > \n', z / 3)

# INT DIVISION
print('\nInt Division --> \n', (z * 100) // 3)

# MOD
print('\nMod --> \n', ((z * 100) // 3) % 2)

# POWER
print('\nPower --> \n', z ** 2)

Addition --> 
 tensor([[3.7445, 3.4892, 3.2426, 3.7003, 3.5277],
        [3.2472, 3.7909, 3.4235, 3.0169, 3.2209],
        [3.9535, 3.7064, 3.1629, 3.8902, 3.5163],
        [3.0359, 3.6476, 3.3430, 3.3182, 3.5261],
        [3.0447, 3.5123, 3.9051, 3.5989, 3.4450]])

Substraction --> 
 tensor([[-0.2555, -0.5108, -0.7574, -0.2997, -0.4723],
        [-0.7528, -0.2091, -0.5765, -0.9831, -0.7791],
        [-0.0465, -0.2936, -0.8371, -0.1098, -0.4837],
        [-0.9641, -0.3524, -0.6570, -0.6818, -0.4739],
        [-0.9553, -0.4877, -0.0949, -0.4011, -0.5550]])

Multiplication --> 
 tensor([[2.9779, 1.9568, 0.9702, 2.8014, 2.1108],
        [0.9887, 3.1635, 1.6939, 0.0676, 0.8836],
        [3.8141, 2.8256, 0.6515, 3.5608, 2.0651],
        [0.1435, 2.5905, 1.3721, 1.2730, 2.1044],
        [0.1786, 2.0494, 3.6203, 2.3954, 1.7800]])

Division -- > 
 tensor([[0.2482, 0.1631, 0.0809, 0.2334, 0.1759],
        [0.0824, 0.2636, 0.1412, 0.0056, 0.0736],
        [0.3178, 0.2355, 0.0543, 0.2967, 0.1721]

## ****2. Element Wise operations****

In [25]:
a = torch.rand(3, 4)
b = torch.rand(3, 4)
c = torch.tensor([-3, 5, -2, 8, -9, 1, -7])


display(a)
display(b)
display(c)

tensor([[0.7278, 0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687, 0.9053],
        [0.8356, 0.3039, 0.6726, 0.5740]])

tensor([[0.9233, 0.9178, 0.7590, 0.7775],
        [0.6179, 0.3379, 0.2170, 0.9454],
        [0.7116, 0.1157, 0.6574, 0.3451]])

tensor([-3,  5, -2,  8, -9,  1, -7])

In [26]:
# ADDITION
print('Addition --> \n', a + b)

# SUBSTRACTION
print('\nSubstraction --> \n', a - b)

# MULTIPLICATION
print('\nMultiplication --> \n', a * b)

# DIVISION
print('\nDivision -- > \n', a / b)

# MOD
print('\nMod --> \n', (a % b))

# POWER
print('\nPower --> \n', a ** b)

# ABSOLUTE
print('\nAbsolute --> \n', torch.abs(c))

# NEGATIVE
print('\nNegative --> \n', torch.neg(c))

# ROUND
print('\nRound --> \n', torch.round(a))

# CEIL
print('\nCeil --> \n', torch.ceil(b))

# FLOOR
print('\nFloor --> \n', torch.floor(b))

# CLAMP
print('\nClamp --> \n', torch.clamp(a, min = 0.1, max = 0.8))

Addition --> 
 tensor([[1.6511, 1.3741, 1.0979, 1.3987],
        [1.1709, 1.0275, 0.5858, 1.8506],
        [1.5471, 0.4196, 1.3300, 0.9191]])

Substraction --> 
 tensor([[-0.1955, -0.4615, -0.4202, -0.1564],
        [-0.0649,  0.3517,  0.1517, -0.0401],
        [ 0.1240,  0.1882,  0.0153,  0.2288]])

Multiplication --> 
 tensor([[0.6720, 0.4188, 0.2572, 0.4830],
        [0.3417, 0.2330, 0.0800, 0.8558],
        [0.5946, 0.0352, 0.4422, 0.1981]])

Division -- > 
 tensor([[0.7883, 0.4971, 0.4464, 0.7989],
        [0.8950, 2.0410, 1.6990, 0.9576],
        [1.1743, 2.6258, 1.0232, 1.6629]])

Mod --> 
 tensor([[0.7278, 0.4563, 0.3389, 0.6211],
        [0.5530, 0.0139, 0.1517, 0.9053],
        [0.1240, 0.0724, 0.0153, 0.2288]])

Power --> 
 tensor([[0.7458, 0.4867, 0.4398, 0.6906],
        [0.6935, 0.8820, 0.8053, 0.9102],
        [0.8800, 0.8712, 0.7705, 0.8256]])

Absolute --> 
 tensor([3, 5, 2, 8, 9, 1, 7])

Negative --> 
 tensor([ 3, -5,  2, -8,  9, -1,  7])

Round --> 
 tensor([[1., 0.,

## ****3. Reduction Operations****

In [27]:
d = torch.randint(size = (3, 4), low = 0, high = 10, dtype = torch.float64)
d

tensor([[4., 7., 2., 3.],
        [8., 5., 6., 2.],
        [9., 5., 0., 4.]], dtype=torch.float64)

In [28]:
# SUM
print('\nSum --> \n', torch.sum(d))

# SUM ALONG COLUMNS
print('\nSum Along Columns --> \n', torch.sum(d, dim = 0))

# SUM ALONG ROWS
print('\nSum Along Rows --> \n', torch.sum(d, dim = 1))


Sum --> 
 tensor(55., dtype=torch.float64)

Sum Along Columns --> 
 tensor([21., 17.,  8.,  9.], dtype=torch.float64)

Sum Along Rows --> 
 tensor([16., 21., 18.], dtype=torch.float64)


In [29]:
# MEAN
print('\nMean --> \n', torch.mean(d))

# MEAN ALONG COLUMNS
print('\nMean Along Columns --> \n', torch.mean(d, dim = 0))


Mean --> 
 tensor(4.5833, dtype=torch.float64)

Mean Along Columns --> 
 tensor([7.0000, 5.6667, 2.6667, 3.0000], dtype=torch.float64)


In [30]:
# MEDIAN
print('\nMedian --> \n', torch.median(d))

# MAX & MIN
print('\nMax --> \n', torch.max(d))
print('\nMin --> \n', torch.min(d))

# PRODUCT
print('\nProduct --> \n', torch.prod(d))

# STANDARD DEVIATION
print('\nStandard Deviation --> \n', torch.std(d))

# VARIANCE
print('\nVariance --> \n', torch.var(d))

# ARGMAX
print('\nArgmax --> \n', torch.argmax(d))

# ARGMIN
print('\nArgmin --> \n', torch.argmin(d))


Median --> 
 tensor(4., dtype=torch.float64)

Max --> 
 tensor(9., dtype=torch.float64)

Min --> 
 tensor(0., dtype=torch.float64)

Product --> 
 tensor(0., dtype=torch.float64)

Standard Deviation --> 
 tensor(2.6443, dtype=torch.float64)

Variance --> 
 tensor(6.9924, dtype=torch.float64)

Argmax --> 
 tensor(8)

Argmin --> 
 tensor(10)


## ****4. Matrix Operations****

In [31]:
e = torch.randint(size = (2, 4), low = 0, high = 15)
f = torch.randint(size = (4, 2), low = 10, high = 25)

display(e)
display(f)

tensor([[12, 12, 11, 11],
        [ 0, 14,  9, 11]])

tensor([[11, 17],
        [19, 17],
        [12, 10],
        [11, 16]])

In [32]:
# MATRIX OPERATIONS
torch.matmul(e, f)

tensor([[613, 694],
        [495, 504]])

In [33]:
vec1 = torch.tensor([1, 4])
vec2 = torch.tensor([3, 5])

# DOT PRODUCT
torch.dot(vec1, vec2)

tensor(23)

In [34]:
# TRANSPOSE
torch.transpose(e, 0, 1)

tensor([[12,  0],
        [12, 14],
        [11,  9],
        [11, 11]])

In [35]:
g = torch.randint(size = (3, 3), low = 1, high = 20, dtype = torch.float64)
g

tensor([[ 8., 12., 18.],
        [10.,  3., 13.],
        [13.,  8.,  1.]], dtype=torch.float64)

In [36]:
# DETERMINANT
torch.det(g)

tensor(1838.0000, dtype=torch.float64)

In [37]:
# INVERSE
torch.inverse(g)

tensor([[-0.0550,  0.0718,  0.0555],
        [ 0.0865, -0.1230,  0.0413],
        [ 0.0223,  0.0501, -0.0522]], dtype=torch.float64)

## ****5. Comparison Operations****

In [38]:
h = torch.randint(size = (5, 6), low = 0, high = 30)
i = torch.randint(size = (5, 6), low = 10, high = 50)

print("h --> \n", h)
print("\ni --> \n",i)

h --> 
 tensor([[ 1,  2, 27,  9,  2,  4],
        [26,  6,  8,  4, 29, 10],
        [27, 29, 12, 17, 10, 12],
        [ 4, 24,  6,  2, 21, 20],
        [25, 11, 20, 10, 12, 12]])

i --> 
 tensor([[13, 17, 31, 35, 10, 42],
        [23, 27, 40, 32, 15, 32],
        [28, 30, 12, 25, 13, 16],
        [37, 48, 11, 12, 13, 42],
        [17, 19, 23, 49, 47, 27]])


In [39]:
# GREATER THAN
print('\nGreater than --> \n', h > i)

# LESS THAN
print('\nLess than --> \n', h < i)

# EQUAL TO
print('\nEqual to --> \n', h == i)

# NOT EQUAL TO
print('\nNot Equal To --> \n', h != i)

# GREATER THAN EQUAL TO
print('\nGreater than equal to --> \n', h >= i)

# LESS THAN EQUAL TO
print('\nLess than equal to --> \n', h <= i)


Greater than --> 
 tensor([[False, False, False, False, False, False],
        [ True, False, False, False,  True, False],
        [False, False, False, False, False, False],
        [False, False, False, False,  True, False],
        [ True, False, False, False, False, False]])

Less than --> 
 tensor([[ True,  True,  True,  True,  True,  True],
        [False,  True,  True,  True, False,  True],
        [ True,  True, False,  True,  True,  True],
        [ True,  True,  True,  True, False,  True],
        [False,  True,  True,  True,  True,  True]])

Equal to --> 
 tensor([[False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False,  True, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False]])

Not Equal To --> 
 tensor([[ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True, False,  True,  Tr

## ****6. Special Functions****

In [40]:
j = torch.randint(size = (3, 4), low = 0, high = 10, dtype = torch.float64)
j

tensor([[5., 9., 2., 2.],
        [4., 8., 9., 6.],
        [1., 4., 5., 6.]], dtype=torch.float64)

In [41]:
# LOG
print('\nLog --> \n', torch.log(j))

# EXPONENT
print('\nExponent --> \n', torch.exp(j))

# SQUARE ROOT
print('\nSquare Root --> \n', torch.sqrt(j))

# SIGMOID
print('\nSigmoid --> \n', torch.sigmoid(j))

# SOFTMAX
print('\nSoftmax --> \n', torch.softmax(j, dim = 0))

# RELU
print('\nReLU --> \n', torch.relu(j))


Log --> 
 tensor([[1.6094, 2.1972, 0.6931, 0.6931],
        [1.3863, 2.0794, 2.1972, 1.7918],
        [0.0000, 1.3863, 1.6094, 1.7918]], dtype=torch.float64)

Exponent --> 
 tensor([[1.4841e+02, 8.1031e+03, 7.3891e+00, 7.3891e+00],
        [5.4598e+01, 2.9810e+03, 8.1031e+03, 4.0343e+02],
        [2.7183e+00, 5.4598e+01, 1.4841e+02, 4.0343e+02]], dtype=torch.float64)

Square Root --> 
 tensor([[2.2361, 3.0000, 1.4142, 1.4142],
        [2.0000, 2.8284, 3.0000, 2.4495],
        [1.0000, 2.0000, 2.2361, 2.4495]], dtype=torch.float64)

Sigmoid --> 
 tensor([[0.9933, 0.9999, 0.8808, 0.8808],
        [0.9820, 0.9997, 0.9999, 0.9975],
        [0.7311, 0.9820, 0.9933, 0.9975]], dtype=torch.float64)

Softmax --> 
 tensor([[7.2140e-01, 7.2748e-01, 8.9468e-04, 9.0747e-03],
        [2.6539e-01, 2.6762e-01, 9.8114e-01, 4.9546e-01],
        [1.3213e-02, 4.9017e-03, 1.7970e-02, 4.9546e-01]], dtype=torch.float64)

ReLU --> 
 tensor([[5., 9., 2., 2.],
        [4., 8., 9., 6.],
        [1., 4., 5., 6.]

# ****Inplace Operations****

In [42]:
k = torch.rand(2, 4)
l = torch.rand(2, 4)

print("\nk --> \n", k)
print('\nl --> \n', l)


k --> 
 tensor([[0.3617, 0.9687, 0.0359, 0.3041],
        [0.9867, 0.1290, 0.6887, 0.1637]])

l --> 
 tensor([[0.0899, 0.3139, 0.1219, 0.3516],
        [0.2316, 0.2847, 0.3520, 0.2828]])


In [43]:
k.add_(l)

# If we use "_" after any function like in above example.
# It works like inplace operation, means it will save operations in "k".
# We can do this with any functions.

tensor([[0.4516, 1.2826, 0.1578, 0.6557],
        [1.2183, 0.4138, 1.0406, 0.4464]])

In [44]:
# EXAMPLE

k.relu_()

tensor([[0.4516, 1.2826, 0.1578, 0.6557],
        [1.2183, 0.4138, 1.0406, 0.4464]])

# ****Copying a Tensor****

In [45]:
m = torch.rand(2, 4)
m

tensor([[0.2420, 0.4928, 0.5772, 0.3771],
        [0.2440, 0.8994, 0.1041, 0.9193]])

In [46]:
n = m
n

tensor([[0.2420, 0.4928, 0.5772, 0.3771],
        [0.2440, 0.8994, 0.1041, 0.9193]])

In [47]:
n = m.clone()
id(n)

135573142083600

In [48]:
id(m)

135573142081520

# ****Tensor Operations on GPU****

In [49]:
torch.cuda.is_available()

True

In [50]:
device = torch.device('cuda')

In [51]:
# Creating New tensor on GPU

torch.rand((2, 5), device = device)

tensor([[0.3563, 0.0303, 0.7088, 0.2009, 0.0224],
        [0.9896, 0.3737, 0.0823, 0.2851, 0.4433]], device='cuda:0')

In [52]:
# Moving an Existing Tensor to GPU
torch.manual_seed(100)
o = torch.rand(2, 4)
o

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [53]:
o.to(device)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]], device='cuda:0')

In [76]:
import torch
import time

# Define the size of metrices
size = 20000                      # Large size for performance comparison

# Create Random matrices un CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time to Complete task on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)   # Matrix Multiplication on CPU
cpu_time = time.time() - start_time

print(f'Time On CPU ==> {cpu_time: 4f} Seconds')


# Move Matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time to complete task on GPU
start_time1 = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)    # Matrix Multiplication on GPU
torch.cuda.synchronize()            # Ensure all GPU operations are complete
gpu_time = time.time() - start_time1

print(f'\nTime On GPU ==> {gpu_time: 4f} Seconds')

# Compare Results
print('\nSpeedup (CPU time / GPU time) : ', cpu_time / gpu_time)

Time On CPU ==>  118.137857 Seconds

Time On GPU ==>  4.794958 Seconds

Speedup (CPU time / GPU time) :  24.637934265605402


# ****Reshaping Tensors****

In [56]:
p = torch.ones(4, 4)
p

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
# RESHAPE
p.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [59]:
# FLATTEN
p.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
q = torch.rand(2, 3, 4)
q

tensor([[[0.7952, 0.6836, 0.5922, 0.2174],
         [0.0420, 0.8548, 0.3101, 0.2836],
         [0.2462, 0.5232, 0.4574, 0.1929]],

        [[0.9183, 0.1421, 0.0330, 0.8051],
         [0.0917, 0.0962, 0.9415, 0.8114],
         [0.6297, 0.3090, 0.9336, 0.9341]]])

In [62]:
# PERMUTE
q.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [67]:
# UNSQUEEZE
r = torch.rand(226, 226, 3)
r.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [68]:
# SQUEEZE
s = torch.rand(1, 30)
s.squeeze(0).shape

torch.Size([30])

# ****Numpy and Pytorch****

In [69]:
import numpy as np

In [70]:
t = torch.tensor([2, 5, 3, 1, 6, 43, 1])
t

tensor([ 2,  5,  3,  1,  6, 43,  1])

In [72]:
u = t.numpy()
print(u, type(u))

[ 2  5  3  1  6 43  1] <class 'numpy.ndarray'>


In [75]:
v = np.array([1, 5, 2, 6, 8, 4, 8])
w = torch.from_numpy(v)
print(w, type(w))

tensor([1, 5, 2, 6, 8, 4, 8]) <class 'torch.Tensor'>
