# ****Plan Of Action****

1. The NN Module
2. The torch.optim Module

## ****1. The torch NN Module****

> The torch NN module in pytorch is a core library that provides wide array of classes and functions designed to help developers to build neural networks effeciently and effectively.It abstracts the complexity of creating & training neural networks by offering pre-built layers, loss functions, activation functions, and other utilities, enabling you to focus on designing and expermenting with the model architectures.

### ****Key Components of torch.nn :****
1. **`Modules (Layers)`**:
      - `nn.Module`: The base class for allneural network modules. Your custom models and layers should subclass this class.

      - `Commonn Layers`: Includes layers like nn.Linear(Fully connected layer), nn.Cov2d (Convolutional laye), nn.LSTM (recurrent layer), and many other.

2. **`Activation Functions`**:
      - Functions like nn.ReLU, nn.Sigmoid, and nn.Tanh introduce nonlinearities to the model, allowing it to learn complex patterns.

3. **`Loss Functions`**:
      - Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss, and nn.NLLLoss to quantify the difference between the models predictions and actual targets.

4. **`Container Module`**:
      - `nn.Sequential`: A Sequential container to stack layers in order.

5. **`Regularization and Dropout`**:
      - Layers like nn.Dropot and nn.BatchNormal2d help prevent overfitting and improve the model's ability to generalize to new data.

In [28]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )


  def forward(self, features):

    out = self.network(features)

    return out

In [29]:
# Create Dataset
features = torch.rand(10, 5)

# Create Model
model = Model(features.shape[1])

# Call Model for forward pass
model(features)

tensor([[0.5692],
        [0.5694],
        [0.5624],
        [0.5676],
        [0.5629],
        [0.5692],
        [0.5692],
        [0.5692],
        [0.5692],
        [0.5638]], grad_fn=<SigmoidBackward0>)

In [23]:
# Show Model Weights
display(model.linear2.weight)

# Show Model Bias
display(model.linear2.bias)

Parameter containing:
tensor([[ 0.0126, -0.3078,  0.4466]], requires_grad=True)

Parameter containing:
tensor([0.0894], requires_grad=True)

In [25]:
!pip install torchinfo

In [24]:
from torchinfo import summary

summary(model, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00